config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todo_items do
    member do
      post 'toggle_complete'
    end
  end

  root 'todo_items#index'

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
  validates :title, length: { minimum: 1 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :todo_items

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_item, only: [:show, :edit, :update, :toggle_complete]
  before_filter :authenticate_user!

  # GET /todo_items
  # GET /todo_items.json
  def index
    #@todo_items = TodoItem.all
    @todo_items = current_user.todo_items
  end

  # GET /todo_items/1
  # GET /todo_items/1.json
  def show
  end

  # GET /todo_items/new
  def new
    @todo_item = TodoItem.new
  end

  # GET /todo_items/1/edit
  def edit
  end

  # POST /todo_items
  # POST /todo_items.json
  def create
    @todo_item = TodoItem.new(todo_item_params)

    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to @todo_item, notice: 'Todo item was successfully created.' }
        format.json { render :show, status: :created, location: @todo_item }
        format.js do
          flash.notice = 'Todo item was successfully created.'
          render :insert
        end
      else
        format.html { render :new }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
        format.js { render :new } # shows the error messages
      end
    end
  end

  # PATCH/PUT /todo_items/1
  # PATCH/PUT /todo_items/1.json
  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to @todo_item, notice: 'Todo item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_item }
        format.js { render :update_row }
      else
        format.html { render :edit }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
        format.js   { render :edit }
      end
    end
  end

  # DELETE /todo_items/1
  # DELETE /todo_items/1.json
  def destroy
    # find_by_id does not raise exception like .find
    @todo_item = TodoItem.find_by_id(params[:id])
    if @todo_item
      @todo_item.destroy
      respond_to do |format|
        format.html { redirect_to todo_items_url, notice: 'Todo item was successfully destroyed.' }
        format.json { head :no_content }
        format.js  do
          flash.notice = "The todo was successfully deleted"
          render :destroy
        end
      end
    else
      respond_to do |format|
        format.js do
          flash.notice = "The selected todo did not exist"
        end
      end
    end
  end

  # POST /todo_items/:id/toggle_complete(.:format)
  def toggle_complete
    @todo_item.is_complete = !@todo_item.is_complete
    @todo_item.save
 #   redirect_to todo_items_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_item
      @todo_item = TodoItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_item_params
      params.require(:todo_item).permit(:title, :is_complete)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>


<%= yield %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for(@todo_item) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :is_complete %><br>
    <%= f.check_box :is_complete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_items/_inline_form.html.erb
<%= form_for(@todo_item, remote: true) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.submit value: 'Save' %>
  </div>
<% end %>

app/views/todo_items/_row.html.erb
      <tr class="todo-item" id="todo_<%= todo_item.id %>">
        <td><%= button_to [:toggle_complete, todo_item], class: 'complete-toggle .toggle', remote: true do %>
          <%= todo_item.is_complete %>
        <% end %></td>
        <td class="label"><%= todo_item.title %></td>
        <td><%= link_to 'Edit', edit_todo_item_path(todo_item), remote: true %></td>
        <td><%= link_to 'Delete', todo_item, method: :delete,
            data: { confirm: 'Are you sure?' }, remote: true %></td>
      </tr>

app/views/todo_items/destroy.js.erb
$('#notice').finish();
<% if @todo_item %>
  $('#todo_<%= @todo_item.id %>').css("text-decoration", "line-through");
  $('#todo_<%= @todo_item.id %>').fadeOut(1000, function() {
    $('#todo_<%= @todo_item.id %>').remove();
  });
<% else %>
  window.location.href = "/";
<% end %>
$('#notice').html('<%= flash[:notice] %>');
//$('#notice').html('the todo was successfully deleted');
$('#notice').fadeOut(4000, function() {
  $('#notice').html('');
  $('#notice').show();
});

app/views/todo_items/edit.html.erb
<h1>Editing Todo Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_item %> |
<%= link_to 'Back', todo_items_path %>

app/views/todo_items/edit.js.erb
$("#todo_<%= @todo_item.id %>").html("<td><%=j render "inline_form" %></td>");

app/views/todo_items/index.html.erb
<section id="todoapp">
  <header id="header">
    <h1>todos</h1>
    <div class="new-item" id="new-item"></div>
    <%= link_to 'New Todo item', new_todo_item_path, remote: true %>
  </header>
  <section id="main">
  <table>
    <thead>
      <tr>
        <th>Done?</th>
        <th>Title</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody id='todo-list'>
      <% @todo_items.each do |todo_item| %>
        <%= render "row", todo_item: todo_item %>
      <% end %>
    </tbody>
  </table>
  </section>
</section>

app/views/todo_items/insert.js.erb
$('#new-item').html("");
$('tbody').append("<%=j render "row", todo_item: @todo_item %>");
$('#notice').html('<%= flash[:notice] %>');
$('#notice').fadeOut(4000, function() {
  $('#notice').html('');
  $('#notice').show();
});

app/views/todo_items/new.html.erb
<h1>New Todo Item</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_items_path %>

app/views/todo_items/new.js.erb
$('#new-item').html("<%=j render 'inline_form' %>");
$('#new-item').show();
//$('#test').slideDown(350);

app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo_item.title %>
</p>

<p>
  <strong>Iscomplete:</strong>
  <%= @todo_item.is_complete %>
</p>

<%= link_to 'Edit', edit_todo_item_path(@todo_item) %> |
<%= link_to 'Back', todo_items_path %>

app/views/todo_items/toggle_complete.js.erb
$('#todo_<%= @todo_item.id %> .complete-toggle').html("<%= @todo_item.is_complete  %>");

app/views/todo_items/update_row.js.erb
$("#todo_<%= @todo_item.id %>").replaceWith("<%=j render "row", todo_item: @todo_item %>");